### ISSUE TITLE
Definition of Supplemental Package

### ISSUE THREAD

**Issue by fschleich** [imfug/002-pkg-and-delivery#11]
The term Supplemental Package is well established with the meaning "non-complete package". See also [Issue #4 ](https://github.com/imfug/002-pkg-and-delivery/issues/4)

I propose the following definition:

An IMF Package (IMP) that depends on additional assets to assemble the entire composition. In technical terms, the CPL(s) of such IMP reference assets that are not included in the same IMP (i.e. not listed in the PKL).

**Comment by jack-watts** [comment]
> In technical terms, the CPL(s) of such IMP reference assets that are not included in the same IMP (i.e. not listed in the PKL).

Keeping this text at the end works for me.

**Comment by palemieux** [comment]
What is the term for a Package that contains one complete Composition (all assets + CPL) plus one additional asset not referenced by the Composition?

**Comment by fschleich** [comment]
> What is the term for a Package that contains one complete Composition (all assets + CPL) plus one additional asset not referenced by the Composition?

I don't know of an established term for such Package. Are you suggesting that a package without a CPL could be called supplemental package?

**Comment by palemieux** [comment]
The [proposed definition for Supplemental Package](https://github.com/imfug/002-pkg-and-delivery/issues/11#issue-664848504) seem to require a CPL but does not explicitly state so. Conversely, it neither explicitly prohibits multiple CPLs nor assets referenced by no CPL in the IMP.

I suggest being more precise.

Does Supplemental Package mean _an Incomplete IMP that, when combined with a given Complete IMP, results only in one or more CPLs and all the assets they reference, no more no less._?

**Comment by fschleich** [comment]
Good points, Pierre. Here's an attempt at clarifying the intent (the actual wording needs tweaking):

_An IMF Package (IMP) that contains one or more CPLs, zero or more Track Files referenced from these compositions and no Track Files that are not referenced from these compositions, but one or more contained CPLs reference one or more Track Files that are not contained in the package._

**Comment by jack-watts** [comment]
Building on Florian's comment and given the wording needed to describe the intent, trying to combine all into a single statement leads to stuttering. Would it be better serviced to defining a supplemental with a list of conditions/criteria? e.g.

> A supplemental package can be described as an IMF Package (IMP) that adheres to one or more of the following criteria;
> 
> - contains one or more CPLs
> - contains zero or more Track Files referenced from a contained CPL
> - contains no Track Files that are not referenced from the contained CPLs
> - contains one or more CPLs that reference one or more Track Files that are not contained in the package

**Comment by jack-watts** [comment]
**Proposed definition:**
An IMF Package that references one or more CPL(s) from its Packing List and missing one or more track files referenced by said CPL(s). The Packing List must not reference any track files not referenced from included CPL(s).

_Closed as per WG agreement in the meeting on August 12th 2020._
