### ISSUE TITLE
Clarify Definition of term - Branched

### ISSUE THREAD

**Issue by jack-watts** [imfug/002-pkg-and-delivery#15]
Current Text:

"Branched
A mastering workflow term used to describe the process of when a CPL’s playout order alternates its track file point of reference, be it to/from the initial track file or to another before referencing the initial once more."

WG proposal:

"Change to 'Branched Assembly'
A mastering workflow term used to describe the process of when a CPL’s playout order alternates its track file point of reference, be it to/from the initial track file or to another before referencing the initial once more."

**Comment by SteveLLamb** [comment]
I'm not sure I can be any less verbose than this. The below is lifted from my definitions used internally (with minor tweaks) for new operators that have zero knowledge of these types of terms. 

-----------

Branching is a mastering workflow that uses additional reels, entry points, and durations within the CPL to create a composition that plays back differently when compared to a "flattened" original version. Often times, the purpose of using this method is to add "insert" shots (textless titles, replacement shots, localized content) in the middle of an already existing contiguous reel asset - whereas the original reel plays, the insert reel(s), and the original reel resumes at the temporal point of the CPL after the duration of the insert (removing the overlapped section of the original reel from playback).

Simplified example for demonstration using a single reel and single branched insert:
- "Flattened" CPL and playback: Original R1 (1-100)
- "Branched" CPL and playback: Original R1 (1-49) > Insert R1 (1-10) > Original R1 (60-100)

**Comment by jack-watts** [comment]
WG agreed on 17-09-2020

Branched assembly is a mastering workflow that uses additional track files, entry points, and durations within the CPL to create a composition that plays back differently when compared to a "flattened" original version. Often times, the purpose of using this method is to add "insert" shots (textless titles, replacement shots, localized content) in the middle of an already existing contiguous track file asset - whereas the original track file plays, the insert track file(s), and the original track file resume at the temporal point of the CPL after the duration of the insert (removing the overlapped section of the original track file from playback).

A simplified example for demonstration using a single track file and single branched insert assembly:

"Flattened" CPL and playback: Original track file (1-100)
"Branched" CPL and playback: Original track file (1-49) > Insert track file (1-10) > Original track file (60-100)
