### ISSUE TITLE
Clarify definition - Composition

### ISSUE THREAD

**Issue by jack-watts** [imfug/002-pkg-and-delivery#18]
Proposal to

- Include the definition of the term Composition from the standard 2067-3:2020
"Embodies a version of a complete work, combining metadata and essence"
- Need to elaborate on the separation of Composition and CPL.xml.

**Comment by jack-watts** [comment]
chat comment from Brian:

"With regards to supplementals, a composition can be composed of essences that are contained in a single package or one or more supplemental packages"

**Comment by dkneeland** [comment]
Proposed definition:

A composition embodies a version of a complete work, combining metadata and essence. Often a composition will be referred to as a CPL, however a CPL is only referring to a single XML file. A composition includes the CPL metadata along with the related essence files.

A composition is not the same as an IMP, as a composition only describes the how the essences are to be combined to a single experience and does not require an assetmap or PKL.

**Comment by jack-watts** [comment]
> A composition embodies a version of a complete work, combining metadata and essence. Often a composition will be referred to as a CPL, however, a CPL is only referring to a single XML file. 

Adding the word virtual to highlight that a composition needs software to make it exist.

"A Composition is a virtual representation embodying a version of a complete work, combining metadata and essence files contained and referenced within the CPL file. Often a composition will be referred to as a CPL, however, a CPL is only referring to a single XML file." 

>A composition includes the CPL metadata along with the related essence files.

This line repeats the leading line of the definition. Opt to remove it?
 
The definition would then read as follows;

"A Composition is a virtual representation embodying a version of a complete work, combining metadata and essence files contained and referenced within the CPL file. Often a Composition will be referred to as a CPL, however, a CPL is only referring to a single XML file.

A Composition is not the same as an IMP, as a Composition only describes how the essences are to be combined to a single experience and does not require an ASSETMAP or PKL."

**Comment by palemieux** [comment]
> Adding the word virtual to highlight that a composition needs software to make it exist.

Actually a composition is a concrete manifestation of the work, as opposed to an edit, which is abstract.

**Comment by jack-watts** [comment]
proposed definition:

"A Composition is a concrete technical manifestation of the work, combining metadata and essence files contained and referenced within the CPL file. Often a Composition will be referred to as a CPL, however, a CPL is only referring to a single XML file.

A Composition is not the same as an IMP, as a Composition only describes how the essences are to be combined to a single experience and does not require an ASSETMAP or PKL."

**Comment by jack-watts** [comment]
WG confirmed 17-09-2020

"A Composition is a concrete technical manifestation of the work, combining metadata and essence files contained and referenced within a single CPL file. Often a Composition will be referred to as a CPL, however, a CPL is only referring to an XML file.

A Composition is not the same as an IMP, as a Composition only describes how the essences are to be combined to a single experience and does not require an ASSETMAP or PKL."
