### ISSUE TITLE
Consolidated Composition vs Flattened Composition

### ISSUE THREAD

**Issue by cconcolato** [imfug/002-pkg-and-delivery#26]
> Consolidation
> A mastering workflow step where the resources of each virtual track within a Composition are merged, and the underlying assets are transwrapped, such that each Virtual Track of the resulting Composition references a single Resource.
>
> Consolidated Composition
> A Composition resulting from Consolidation.
>
> Flattened Composition
> A flattened composition is a composition where each virtual track consists of a single resource.

Am I missing something or are Consolidated and Flattened synonymous? If so, it should be explicit.

**Comment by jack-watts** [comment]
@cconcolato Yes, you are correct. However, given the context in which the terms are used i.e. In a W/O at a facility, you could see the following;

**Instruction 1**
> Please create a flattened composition from composition A

**Instruction 2**
> Including timed-text B, please consolidate composition A to create a flattened composition.

Instruction 2 provides a clearer scope to an operator as to what actions they would need to perform in a mastering appliance to achieve a flattened state.

**Comment by jack-watts** [comment]
WG 20201014 proposes to add an explicit statement at the end of each definition to indicate the same result.

Consolidation
A mastering workflow step where the resources of each virtual track within a Composition are merged, and the underlying assets are transwrapped, such that each Virtual Track of the resulting Composition references a single Resource.

Consolidated Composition
A Composition resulting from Consolidation. This term is synonymous to flattened composition. 

Flattened Composition
A flattened composition is a composition where each virtual track consists of a single resource. This term is synonymous to consolidated composition.
