### ISSUE TITLE
Clarify definition of Complete IMP

### ISSUE THREAD

**Issue by jack-watts** [imfug/002-pkg-and-delivery#3]
Porting the conversation from [2067-2, Issue #39](https://github.com/SMPTE/st2067-2/issues/39)

**Comment by fschleich** [comment]
To make the current definition a bit easier to digest, I propose:

An IMF Package (IMP) that contains all media assets required to assemble the entire composition. In technical terms, the Packing List (PKL) of such IMP includes all assets that comprise the included CPL(s).

**Comment by jack-watts** [comment]
+1

**Comment by bholter** [comment]
I think the first line should end with "assemble the composition(s)". Unless the term composition is used to encapsulate all included CPL(s), which i think is misleading.

**Comment by jack-watts** [comment]
**proposed definition:**

An IMF Package that references one or more CPL(s) from its Packing List as well as all track files referenced by said CPL(s). 

_Closed as per WG agreement in the meeting on August 12th 2020._
