### ISSUE TITLE
Term - Manufacturing vs Mastering

### ISSUE THREAD

**Issue by jack-watts** [imfug/002-pkg-and-delivery#36]
Two words; manufacturing and mastering, both convey the same meaning; the creation of an IMF Composition. Manufacturing appears more prevalent on the studio side whilst mastering is commonplace on the servicing side.

Which term would contributors/users like to see as the primary word used?

**Comment by bholter** [comment]
If we are choosing one over the other my vote would be manufacturing as a term to describe the activity of building a composition which may include track file creation and repurposing. Mastering is a widely used industry term that certainly has a place in IMF, but from my perspective and experience often ends up being a point of confusion when used to describe a process of making a composition.

**Comment by jack-watts** [comment]
WG agrees to use the term Manufacturing as of meeting 20210317
