### ISSUE TITLE
UC - CPL Metadata Changes Table

### ISSUE THREAD

**Issue by jack-watts** [imfug/002-pkg-and-delivery#39]
Table 1 covers the User Editable Metadata Fields. Feedback suggests that the table be re-worked to include potential issues and remediation column.

Working Draft: [View](https://docs.google.com/document/d/1M1qQR-KtucyJKXZV-7h8YGYWP5wkyL7wtWKPUeBRvKk)

**Comment by jack-watts** [comment]
highlight Language value is not related to the Audio language reflected in the Audio MXF track file.
@fschleich to propose text to use.

**Comment by fschleich** [comment]
Proposed footnote for "Language" in "Element Name" column:

> Note that Language element values are not necessarily equal to the spoken and/or written language of the underlying essence. Spoken and written language identifiers are derived from referenced MXF track files. Any update/change to such identifier therefore requires re-packaging of the associated MXF track file.

**Comment by Insanitygift** [comment]
Proposed update to Florian's suggestion:

Note that Language element values are intended to indicate the territory and primary language of that territory, and are not necessarily equal to the spoken and/or written language of the underlying essence. Spoken and written language identifiers are derived from referenced MXF track files with corresponding RFC5646 Spoken Language MCA Labels. Any update/change to such identifier therefore requires re-packaging of the associated MXF track file.

**Comment by jack-watts** [comment]
WG Agrees 20210317
