### ISSUE TITLE
Agree on terms - Complete & Partial

### ISSUE THREAD

**Issue by jack-watts** [imfug/002-pkg-and-delivery#4]
In light of the language used to clarify whether assets are simply 'included' or 'excluded' in a Packing List. As a group, can we agree to limit the top-level terms that describe a Package to be either **Complete** or **Partial**?

**Comment by fschleich** [comment]
I agree with the term "Complete", but the term "Supplemental" is very established to describe what you're referring to as "Partial". Even tools like R&S Clipster and DaVinci Resolve use it in the UI.

![Screen Shot 2020-07-23 at 4 17 35 PM](https://user-images.githubusercontent.com/9813928/88347767-6536b680-cd00-11ea-8f50-2d6bcc5d44ad.png)

**Comment by jack-watts** [comment]
My concern with this hits further down the line when systems start to communicate with each other in a more dynamic way. Its alludes to the example we discussed offline, which I'll reiterate here;

>Taking interchange of assets in a MAM environment as an example; Entity A. has all MXF resource ingested and tracked (i.e. same storage pool, side by side with the respective CPL). Entity B requests only the French Subtitle Version but does not have any of the OV assets defined in the English OV CPL. Entity A’s system would then generate a PKL including all required MXF resources by the French Subtitle version within a single AssetList in said PKL, ready for delivery to Entity B. Therefore, the French Subtitle version, which originally was delivered to Entity A as a Supplemental (Partial) Package is being sent to Entity B as a Complete package. 

I've experienced implementers in the past taking recommendations as gospel and implementing them programmatically. There is a possibility that people could implement the interchange of Supplementals to only being packaged as incomplete given that the established understanding is for supplementals to be 'partial'. I appreciate that the transaction in my example would take place at the system level and not by a human, but humans would be the ones to interpret any definitions and implement against them.

**Comment by bholter** [comment]
Jack if I recall correctly there was a dispute between supplemental as a package and supplemental as a content type. I would think if we refer to complete the accompanying name would be something like "partial" but calling it supplemental is not a hill to die on in opposition for me.

+1 on your MAM example.

**Comment by jack-watts** [comment]
> If I recall correctly there was a dispute between supplemental as a package and supplemental as a content type

Yes, but the use of the term in regard to the Composition content should not be confused with its use in regards to packaging. They are two different categories in my opinion. That said, we need to ensure that we clarify this, probably best suited as a footnote to the Supplemental Packaging definition.

>  I would think if we refer to complete the accompanying name would be something like "partial" but calling it supplemental is not a hill to die on in opposition for me.

I think we're stuck between a rock and a hard place on this. i.e the actual English definition of the words in everyday language use vs the nature in which they have evolved within industry trends.

**Comment by jack-watts** [comment]
@bholter This thread is been closed as it includes discussion beyond that of just Complete and Partial. Regarding your comment, please see the following issue: [https://github.com/imfug/002-pkg-and-delivery/issues/12](https://github.com/imfug/002-pkg-and-delivery/issues/12)
