### ISSUE TITLE
UC - MCA Changes

### ISSUE THREAD

**Issue by jack-watts** [imfug/002-pkg-and-delivery#41]
Current Text:

> A common occurrence during the manufacturing process of a composition is the writing of the language tag in the MXF metadata whereby the language tag should correspond to the spoken dialogue of the underlying sound essence.
> 
> Given the presence of the language tag being in the MXF metadata, all sound essence needs to be re-wrapped, with a new MXF track file being created to include the updated language tag. This will result in a new package being required with a new Composition Playlist including updated references to the newly created MXF sound track files. 
> 
> Together with the existing picture track files, the composition can be repurposed in a new complete package, or referenced from a supplemental package that only contains the new Composition Playlist, a Packing List, Assetmap and the newly created sound track files.
> 
> NOTE: As MCA properties are populated upon creation of an MXF track file, it is recommended that a user observes the practices outlined in IMFUG BP 004 MCA Best Practices.

Working Draft: [View](https://docs.google.com/document/d/1M1qQR-KtucyJKXZV-7h8YGYWP5wkyL7wtWKPUeBRvKk)

**Comment by fschleich** [comment]
Suggested re-wording:

> A language tag is embedded in the MXF metadata of sound track files, identifying the spoken dialogue of the underlying sound essence. Given that the language tag is embedded in the MXF metadata, updating/changing the language tag requires re-wrapping of all sound essence included in the associated track file.
> 
> The resulting sound track file(s) can be referenced from new Composition Playlists (CPL). The updated sound track file(s) and CPL(s) can be packaged in a new complete packages with the original picture track files, or as a supplemental package that only contains the new Composition Playlist, a Packing List, Assetmap and the newly created sound track files.
> 
> NOTE: IMFUG BP 004 MCA Best Practices provides some guidance on how to choose MCA properties.

**Comment by jack-watts** [comment]
WG agrees on text 20210203.
