### ISSUE TITLE
Language tag in Essence Descriptor should not change

### ISSUE THREAD

**Issue by palemieux** [imfug/002-pkg-and-delivery#48]
> A language tag is embedded in the MXF metadata of sound track files, identifying the spoken dialogue of the underlying sound essence. Given that the language tag is embedded in the MXF metadata, updating/changing the language tag requires re-wrapping of all sound essence included in the associated track file.

Why would the language tag need to change if the essence does not change?

**Comment by fschleich** [comment]
Operators occasionally select the wrong language tag and this is to clarify that changing the language in the CPL is not the way to fix such mistake.

**Comment by palemieux** [comment]
> Operators occasionally select the wrong language tag and this is to clarify that changing the language in the CPL is not the way to fix such mistake.

I would say that explicitly, i.e. changing the language code in the Track File is only necessary when it was set in error in the first place.

**Comment by jack-watts** [comment]
Proposed change:

"A language tag is embedded in the MXF metadata of sound track files, identifying the spoken dialogue of the underlying sound essence. Given that the language tag is embedded in the MXF metadata, if it set incorrectly then updating/changing the language tag requires re-wrapping of all sound essence included in the associated track file."
