### ISSUE TITLE
Clarify definition of term Supplemental

### ISSUE THREAD

**Issue by jack-watts** [imfug/002-pkg-and-delivery#5]
IMF has resulted in the term supplemental becoming a polyseme word. It was recommended the term supplemental should be presented with unique definitions dependent on its conjugative use. The terms 'Supplemental Composition' and 'Supplemental Package' have now been added.

**Comment by fschleich** [comment]
In the context of IMF, my strong preference is to only use the term "supplemental" to describe the "non-complete nature" of an IMF Package. 

I recommend removing the current definition of "supplemental" (that refers to the CPL ContentKind value) from the document, as a CPL with a ContentKind value of "supplemental" should not simply be referred to as "supplemental" or "supplemental CPL". Other ContentKind values (e.g. "test", "transitional", "short", "rating", ...) wouldn't be used that way either.

**Comment by jack-watts** [comment]
> I recommend removing the current definition of "supplemental" (that refers to the CPL ContentKind value) from the document, as a CPL with a ContentKind value of "supplemental" should not simply be referred to as "supplemental" or "supplemental CPL". Other ContentKind values (e.g. "test", "transitional", "short", "rating", ...) wouldn't be used that way either.

It is because of the ContentKind value that I felt the need to include it so as to highlight its use elsewhere in IMF other than packaging. Though with your new wording of

> In the context of IMF, my strong preference is to only use the term "supplemental" to describe the "non-complete nature" of an IMF Package.

I am happy to cave on this with the use of the word "supplemental" in the document to be solely packaging related.

**Comment by jack-watts** [comment]
As per the meeting on August 12th, 2020, the WG proposes the **removal** of the term `supplemental`.

Reasoning: Adds confusion by including CPL descriptions...

There is now a two week period for interested parties to comment.
Action will be decided in the next meeting w/c August 2th 2020.

**Comment by jack-watts** [comment]
Closed as per WG agreement in the meeting on August 26th 2020.
