### ISSUE TITLE
Only the playable region is in the CPL

### ISSUE THREAD

**Issue by palemieux** [imfug/002-pkg-and-delivery#51]
In the "Timeline trimming" figure, suggest showing only the playable region in the CPL, and showing both the playable and trimmed regions in track files underneath the CPL.

**Comment by jack-watts** [comment]
Proposed diagram with an amended Figure caption

<img width="495" alt="Screenshot 2021-05-18 at 11 24 15" src="https://user-images.githubusercontent.com/48413193/118635520-9ae6e780-b7cb-11eb-9e01-0211fc780323.png">

Figure 1 – CPL Timeline Trimming example showcases the unchanged state of the referenced MXF track files, but rather the amended duration values of the Virtual Sequence resulting in a shorter playable region.

**Comment by palemieux** [comment]
Couple of suggestions:

* video -> image
* playable region is applied to the track file
* the track files are not included in the composition playlist

![image](https://user-images.githubusercontent.com/4871350/120721615-0f37b100-c483-11eb-8d25-0c1fbcc8f68f.png)
