### ISSUE TITLE
Figure Captions - not clear on meaning

### ISSUE THREAD

**Issue by SteveLLamb** [imfug/002-pkg-and-delivery#56]
All captions for Figures 1-3 in the document have extended prose. Perhaps captions should be shorter and then prose should be adjusted to move to main body and then to reference the figures, such as how was done with Table 1, to help with readability.

**Comment by jack-watts** [comment]
+1 upon re-reading it. It will be included in the next PR.
In addition, it would be presented better if Notes 4 &5 were placed below their respective figures.

thoughts?

**Comment by SteveLLamb** [comment]
> +1 upon re-reading it. It will be included in the next PR.
> In addition, it would be presented better if Notes 4 &5 were placed below their respective figures.
> 
> thoughts?

Ah, that makes more sense reading the notes like that. Yes, agreed.
