### ISSUE TITLE
3.3.1 - confusing repetitive table reference wording

### ISSUE THREAD

**Issue by SteveLLamb** [imfug/002-pkg-and-delivery#60]
"In order to avoid editing structural metadata derived from referenced essence, a table is provided for reference in Section 6.3.2, Table 1 - User Editable Metadata Fields. This table depicts the fields that are permitted to be directly edited by a user after or during the creation of a CPL file."

change to:

"In order to avoid editing structural metadata derived from referenced essence, _Table 1 [add link] - "User Editable Metadata Fields" is provided for reference_. This table depicts the fields that are permitted to be directly edited by a user after or during the creation of a CPL file."

**Comment by jack-watts** [comment]
Noted, will revise and include in next PR.
